spring.application.name=ShoeApp

# Oracle Database connection
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=SHKVLNC
spring.datasource.password=password

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT secret (for later security setup)
jwt.secret=your_jwt_secret_key_here